name = "farallon"
compatibility_date = "2023-12-01"
main = "src/index.ts"
minify = true

[vars]
DOMAIN = "https://bigfa.github.io"
PAGESIZE = 10

[[kv_namespaces]]
binding = "FARALLON"
id = "902c4a30bd8f443aae918da62e3d0c90"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "hugo-cf-worker"

[[d1_databases]]
binding = "DB"
database_name = "hugo-cf-worker"
database_id = "91a8d4e1-af36-4579-93ea-c471bb823635"

# [ai]
# binding = "AI"
